import com.vanniktech.maven.publish.AndroidSingleVariantLibrary

// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    id("com.android.application") version "8.10.1" apply false
    id("com.android.library") version "8.10.1" apply false
    id("dev.rikka.tools.refine") version "4.4.0" apply false
    id("com.vanniktech.maven.publish") version "0.34.0" apply false
}

allprojects {
    tasks.withType(Javadoc) {
        options.addStringOption('Xdoclint:none', '-quiet')
        options.addStringOption('encoding', 'UTF-8')
        options.addStringOption('charSet', 'UTF-8')
    }
}

subprojects {
    afterEvaluate { project ->
        if (!plugins.hasPlugin('com.vanniktech.maven.publish')) {
            return
        }

        if (project.parent == rootProject) {
            group = "${groupIdBase}"
        } else {
            group = "${groupIdBase}.${project.parent.name}"
        }

        def versionName = "hidden-${project.name}"

        version = "1.0.2"
        println("${project.displayName}: ${group}:${versionName}:${version}")

        mavenPublishing {
            configure(new AndroidSingleVariantLibrary("release", true, true))

            publishToMavenCentral(true)
            signAllPublications()

            coordinates(project.group, versionName, project.version)

            pom {
                name = POM_NAME
                description = POM_DESCRIPTION
                inceptionYear = POM_INCEPTION_YEAR
                url = POM_URL

                licenses {
                    license {
                        name = POM_LICENCE_NAME
                        url = POM_LICENCE_URL
                    }
                }

                developers {
                    developer {
                        name = POM_DEVELOPER_NAME
                        url = POM_DEVELOPER_URL
                    }
                }

                scm {
                    url = POM_SCM_URL
                    connection = POM_SCM_CONNECTION
                    developerConnection = POM_SCM_DEV_CONNECTION
                }
            }
        }

        publishing {
            repositories {
                maven {
                    name 'Local'
                    url rootProject.uri("repo")
                }
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    groupIdBase = "com.sunxiaodou.android"

    POM_INCEPTION_YEAR = "2025"
    POM_PACKAGING = "aar"

    POM_URL = "https://github.com/guodongAndroid/HiddenApi"
    POM_SCM_URL = "https://github.com/guodongAndroid/HiddenApi"
    POM_SCM_CONNECTION = "scm:git@github.com:guodongAndroid/HiddenApi.git"
    POM_SCM_DEV_CONNECTION = "scm:git@github.com:guodongAndroid/HiddenApi.git"

    POM_LICENCE_NAME = "MIT License"
    POM_LICENCE_URL = "https://github.com/guodongAndroid/HiddenApi/blob/master/LICENSE"
    POM_LICENCE_DIST = "repo"

    POM_DEVELOPER_ID = "guodongAndroid"
    POM_DEVELOPER_NAME = "guodongAndroid"
    POM_DEVELOPER_URL = "https://github.com/guodongAndroid"
}
