plugins {
    id('com.android.library')
    id('com.vanniktech.maven.publish')
    id('dev.rikka.tools.refine')
}

android {
    namespace = "rikka.hidden.compat"
    buildFeatures {
        buildConfig false
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    annotationProcessor libs.refine.annotation.processor
    implementation libs.refine.annotation
    implementation libs.refine.runtime

    compileOnly libs.androidx.annotation
    implementation(libs.buildcompat) {
        exclude group: 'androidx.annotation', module: 'annotation'
    }
    implementation libs.parcelablelist

    compileOnly project(':stub')
}

ext {
    POM_NAME = "HiddenApiCompat"
    POM_DESCRIPTION = "HiddenApiCompat"
}
